application: als-project
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /templates
  static_dir: templates
  application_readable: true

- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /items/add
  script: handlers.items.add.app

- url: /auctions/add
  script: handlers.auctions.add.app

- url: .*
  script: main.app

libraries:
- name: webapp2
  version: "2.5.2"

- name: jinja2
  version: "latest"
