runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /templates
  static_dir: templates
  application_readable: true

- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /profile/.*
  script: user_profile.apt
  login: required
  auth_fail_action: redirect

- url: /options
  script: handlers.options.app
  login: required

- url: /items
  script: handlers.items.app
  login: required

- url: /items/add
  script: handlers.items.add.app
  login: required

- url: /items/delete
  script: handlers.items.delete.app
  login: required

- url: /auctions
  script: handlers.auctions.app
  login: required

- url: /auctions/add
  script: handlers.auctions.add.app
  login: required

- url: /auctions/delete
  script: handlers.auctions.delete.app
  login: required

- url: /expenses
  script: handlers.expenses.app
  login: required

- url: .*
  script: main.app

libraries:
- name: webapp2
  version: "2.5.2"

- name: jinja2
  version: "latest"

